In [1]:
import numpy as np
import torch

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets expectations (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')


In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
# creating random number of Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)
        

tensor([[-0.6152,  0.7633,  2.3728],
        [ 0.3711, -1.0946, -1.0055]], requires_grad=True)
tensor([-0.9298, -0.5687], requires_grad=True)


In [6]:
# Our model is simply a function that performs a matrix multiplication of the inputs and the 
# weights w (transposed) and adds the bias b (replicated for each observation).
#the formula we use for linear regression: MATRIX x Weight_Transpose + Bias

In [7]:
def model(x):
    return x @ w.t() + b

In [8]:
#generation of prediction
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 107.3314,  -90.0563],
        [ 162.1153, -127.4797],
        [ 185.4505, -173.2840],
        [  56.9360,  -46.9900],
        [ 195.9920, -150.4342]], grad_fn=<AddBackward0>)


In [9]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [10]:
# Calculate the difference between the two matrices (preds and targets).
# Square all elements of the difference matrix to remove negative values.
# Calculate the average of the elements in the resulting matrix.

# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [11]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(27477.8281, grad_fn=<DivBackward0>)


In [12]:
# Compute gradients
loss.backward()

In [14]:
# Gradients for weights
print(w)
print(w.grad)


tensor([[-0.6152,  0.7633,  2.3728],
        [ 0.3711, -1.0946, -1.0055]], requires_grad=True)
tensor([[  5377.9609,   5982.2402,   3810.9668],
        [-17256.0820, -20269.8574, -12247.5234]])


In [16]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [18]:
# Steps which we will follow
# Generate predictions
# Calculate the loss
# Compute gradients w.r.t the weights and biases
# Adjust the weights by subtracting a small quantity proportional to the gradient
# Reset the gradients to zero

preds = model(inputs)
print(preds)

tensor([[ 107.3314,  -90.0563],
        [ 162.1153, -127.4797],
        [ 185.4505, -173.2840],
        [  56.9360,  -46.9900],
        [ 195.9920, -150.4342]], grad_fn=<AddBackward0>)


In [20]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)


tensor(27477.8281, grad_fn=<DivBackward0>)


In [23]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [25]:
print(w)
print(b)

tensor([[-0.6690,  0.7035,  2.3347],
        [ 0.5437, -0.8919, -0.8831]], requires_grad=True)
tensor([-0.9304, -0.5666], requires_grad=True)


In [27]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(18937.2031, grad_fn=<DivBackward0>)


In [30]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [32]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(132.9949, grad_fn=<DivBackward0>)


In [34]:
# Predictions
preds

tensor([[ 55.7436,  73.1533],
        [ 90.3497,  96.1776],
        [102.4561, 138.6016],
        [ 14.6453,  53.4491],
        [119.6579, 101.6208]], grad_fn=<AddBackward0>)

In [44]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [45]:
# Doing the same thing with pytorch libraries
# Input (temp, rainfall, humidity)
import torch.nn as nn
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [40]:
from torch.utils.data import TensorDataset
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]


(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [41]:
from torch.utils.data import DataLoader
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [42]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.]])
tensor([[ 81., 101.],
        [ 22.,  37.],
        [119., 133.],
        [103., 119.],
        [ 56.,  70.]])


In [46]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.0944, -0.1038, -0.4182],
        [ 0.0789, -0.2688, -0.2269]], requires_grad=True)
Parameter containing:
tensor([-0.4457,  0.1728], requires_grad=True)


In [48]:
list(model.parameters())


[Parameter containing:
 tensor([[-0.0944, -0.1038, -0.4182],
         [ 0.0789, -0.2688, -0.2269]], requires_grad=True),
 Parameter containing:
 tensor([-0.4457,  0.1728], requires_grad=True)]

In [50]:
# Generate predictions
preds = model(inputs)
preds

tensor([[-32.2712, -21.8291],
        [-44.9311, -30.8174],
        [-46.8172, -42.1359],
        [-30.0105, -11.7274],
        [-46.1927, -36.0659],
        [-32.2712, -21.8291],
        [-44.9311, -30.8174],
        [-46.8172, -42.1359],
        [-30.0105, -11.7274],
        [-46.1927, -36.0659],
        [-32.2712, -21.8291],
        [-44.9311, -30.8174],
        [-46.8172, -42.1359],
        [-30.0105, -11.7274],
        [-46.1927, -36.0659]], grad_fn=<AddmmBackward>)

In [51]:
# Import nn.functional
import torch.nn.functional as F

In [52]:
# Define loss function
loss_fn = F.mse_loss

In [53]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(15901.0137, grad_fn=<MseLossBackward>)


In [54]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [55]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [56]:
fit(100, model, loss_fn, opt)

Epoch [10/100], Loss: 412.9157
Epoch [20/100], Loss: 449.6605
Epoch [30/100], Loss: 419.1114
Epoch [40/100], Loss: 76.8454
Epoch [50/100], Loss: 58.8452
Epoch [60/100], Loss: 7.2671
Epoch [70/100], Loss: 45.7068
Epoch [80/100], Loss: 61.9697
Epoch [90/100], Loss: 32.1372
Epoch [100/100], Loss: 8.2949


In [57]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.7486,  72.1949],
        [ 79.5041,  98.0627],
        [123.0839, 136.9028],
        [ 29.7078,  46.5847],
        [ 92.0397, 108.9762],
        [ 58.7486,  72.1949],
        [ 79.5041,  98.0627],
        [123.0839, 136.9028],
        [ 29.7078,  46.5847],
        [ 92.0397, 108.9762],
        [ 58.7486,  72.1949],
        [ 79.5041,  98.0627],
        [123.0839, 136.9028],
        [ 29.7078,  46.5847],
        [ 92.0397, 108.9762]], grad_fn=<AddmmBackward>)

In [58]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])