In [2]:
import torch
import numpy as np

In [3]:
#number
t1=torch.tensor([1.])
t1

tensor([1.])

In [4]:
#vector
t2=torch.tensor([1.,2,3,4])
t2
#this converts all the data into one particular type


tensor([1., 2., 3., 4.])

In [5]:
#matrix
t3=torch.tensor([[1,2],[3,4],[5,6]])
t3

# t3=torch.tensor([],[])
# t1.dtype

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [6]:
#3d array
t4=torch.tensor([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
    
])
t4.dtype

torch.int64

In [7]:
#the difference between that tensor can should have regular shape
t4.shape

torch.Size([2, 2, 2])

In [8]:
#tensor operations and gradients
#one can mmix tensors with the regular arithmetic operations
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)
sum=x*w+b
sum
#we can calculate derivative of any functionor a variable with respect to those variable which has the value of requires_grade set to true
#derivative is important for an optimization algorithm called grdient descent

# So,for example if we do the derivative of varible y, then the w.r.t to any input tensor will be stored in the .grad property of that particular tensor.
sum.backward()
#this backard method helps us to compute the derivatives of sum wrt those values which have grad value set as true
#why do we need requires_grad?
#this is for the optimization process, as each gradient calculation has certain cost and when we deal with large models, many parameters, each gradient calculation can make the model slow
#gradient is other name for derivative, it is called so when we are dealing with matrices, else wen it is numbers, we call it derivative.
print('dsum/dx: ',x.grad)
print('dsum)/dw: ',w.grad)
print('dsum/db: ',b.grad)


dsum/dx:  None
dsum)/dw:  tensor(3.)
dsum/db:  tensor(1.)


#numpy has matplot for plotting and visualization, OpenCV for image and video processing, and Pandas for file input ooutput and data analysis
#interoperability of numpy
import numpy as np
x=np.array([[1,2],[3,4]])
#conversion from numpy array to a tensor can lso be done
# y-torch.from_numpy(x)

#pytorch is for graphics
#any code to run on GPU are to be written in kuda and pytorch is used to send the 
#data to the gpu for processing and that is the reason why we use torch instead of array.



In [22]:
# #exercise
# a=torch.tensor([[1.,2,3],[4,5,60],[8,9,0]])
# # b=torch.tensor(5.,requres_grad = True)
# hello=3*a
# hello.backward()                
# print("dz/db ",b.grad)

TypeError: tensor() got an unexpected keyword argument 'requres_grad'

In [24]:
# Code in C or Kuda is very fast so dont use lops in pyrhon, instead use torch for loop
# The learning part of linear regression is to figure out a set of weights w11, w12,... w23, b1 & b2 by looking at the training data, 
# to make accurate predictions for new data (i.e. to predict the yields for apples and oranges in a new region using the average 
# temperature, rainfall and humidity). This is done by adjusting the 
# weights slightly many times to make better predictions, using an optimization technique called gradient descent.
